parameters:
#    web.example.class: Application\Success\WebBundle\Example

services:
#    web.example:
#        class: %web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
