stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            uploadable: true
            tree: true
            translatable: true