sonata_seo:
    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title:            IT Success [Symfony2]
        metas:
            name:
                keywords:             symfony, demo, web, success, itsuccess
                description:          Punto de partida para instalar una aplicacion usando symfony2
                robots:               symfony, demo, web, success, itsuccess

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       IT Success [Symfony2]
                'og:description':     Punto de partida para instalar una aplicacion usando symfony2

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"

