parameters:
#    custom.example.class: Application\Sonata\CustomBundle\Example

services:
#    custom.example:
#        class: %custom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
