#parameters:
#    frequence_web_contact.type.class: Portfolio\FrontendBundle\Form\ContactType
#    frequence_web_contact.model.class: Portfolio\FrontendBundle\Form\Model\Contact
#    frequence_web_contact.email_listener.class: Portfolio\FrontendBundle\EventDispatcher\Listener\EmailContactListener
  
frequence_web_contact:
    send_mails: true                    # True to use the bundle EmailListener that send emails when contact form is submited
    to:         sg@pie-derecho.com.uy   # The contact mail recipient
    from:       sg@pie-derecho.com.uy   # The contact mail sender
    subject:    contact.message.new     # The contact mail subject translation key
