stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: "tinymce"
    language: %locale%
    theme:
        simple:
            mode: "textareas"
            theme: "advanced"
