parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     dbname
    database_user:     root
    database_password: 12345

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    locales:           [en, es]
    secret:            ThisTokenIsNotSoSecretChangeIt
