Application\Success\CoreBundle\Entity\Productora:
    type: entity
    table: success_productora
    gedmo:
       soft_deleteable:
         field_name: deletedAt
         time_aware: false
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 128
            nullable: false
        slug:
            type: string
            length: 256
            nullable: false
            gedmo:
                slug:
                    unique: true
                    separator: "-"
                    style: camel
                    fields: [name]
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
