Application\Success\CoreBundle\Entity\Timeline:
    type: entity
    table: success_timeline
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        action:
            targetEntity: Application\Success\CoreBundle\Entity\Action
            joinColumn:
                name: action_id
                referencedColumnName: id
        subject:
            targetEntity: Application\Success\CoreBundle\Entity\Component
            joinColumn:
                name: subject_id
                referencedColumnName: id
                onDelete: CASCADE
