Application\Success\CoreBundle\Entity\Vote:
    type: entity
    table: success_vote
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        voter:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: []
            nullable: false
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE      
        comment:
            targetEntity: Application\Success\CoreBundle\Entity\Comment
            cascade: []
            nullable: false
            joinColumn:
                name: comment_id
                referencedColumnName: id
                onDelete: CASCADE
  