radio:
    url: 'http://local.justrave.com/uploads/radio/justrave.pls'
    description: 'Guns N´ Roses - Live And Let Die - Destruction, Lies'
promo:
    key: 'MANDÁ JUST AL 64665'
    description: '//////  Guns N´ Roses - Live And Let Die - Destruction, Lies  /////  Guns N´ Roses - Live And Let Die - Destruction, Lies  /////'
