fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\Success\CoreBundle\Entity\Comment
            thread: Application\Success\CoreBundle\Entity\Thread
            vote: Application\Success\CoreBundle\Entity\Vote
#    service:
#        markup: your_markup_service