#services:
#    login_listener:
#        class: Application\Success\UsuarioBundle\Listener\LoginListener
#        scope: request
#        arguments: [@security.context, @router]
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login }
#            - { name: kernel.event_listener, event: kernel.response }
services:
    ###############################################    
    #FORMULARIO DE REGISTRO
    ###############################################  
    success.registration.form.type:
        class: Application\Success\UsuarioBundle\Form\Type\UsuarioRegistroType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: success_user_registration }

    success.form.handler.registration:
        class: Application\Success\UsuarioBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false

    ###############################################    
    #FORMULARIO PROFILE
    ###############################################
    success.profile.form.type:
        class: Application\Success\UsuarioBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: success_user_profile }

    success.form.handler.profile:
        class: Application\Success\UsuarioBundle\Form\Handler\ProfileFormHandler
        arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false

    ###############################################    
    #USER MANAGER
    ###############################################
    success.user.manager:
        class: Application\Success\UsuarioBundle\Doctrine\UserManager
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %fos_user.model.user.class%]
        public: false